services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: npm run dev
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3001
      CHOKIDAR_USEPOLLING: "1"
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_TEXT_MODEL: ${OPENAI_TEXT_MODEL:-gpt-4o-mini}
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    ports:
      - "3001:3001"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0 --port 5173
    working_dir: /app
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: 'http://localhost:3001'
      CHOKIDAR_USEPOLLING: "1"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  api_node_modules:
  web_node_modules:
